name = "ns-cache"
main = "src/main.ts"
compatibility_date = "2023-09-18"

[vars]
ENVIRONMENT = "prod"
TOKEN = "zj5jyr4wqps4xfaiviy5!"
DATABASE_HOST = "us-west.connect.psdb.cloud"
DATABASE_NAME = "fawlmain"
DATABASE_USERNAME = "zj5jyr4wqps4xfaiviy5"

[[kv_namespaces]]
binding = "NSCACHE"
id = "1ebb58a2f6cb41edb82a44905aad19a1"